name = "moonlight-worker-api"
main = "src/index.ts"
compatibility_date = "2026-07-15"

[[d1_databases]]
binding = "DB"
database_name = "moonlight-cms"
database_id = "f561f64e-ea16-4d04-ad15-7bc9333ef823"

[vars]
CLIENT_ORIGIN = "http://localhost:5173"
CLOUDINARY_UPLOAD_FOLDER = "moonlight-cms"
ADMIN_ROLE = "owner"
